name: betclic_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.1.0

  provider: 6.1.4
  flutter_bloc: 9.1.0
  freezed: 3.0.6

  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1

  dio: 5.8.0+1
  retrofit: 4.4.2
  json_annotation: 4.9.0

  go_router: 15.1.1

  hive_ce: 2.10.1
  hive_ce_flutter: 2.2.0

  get_it: 8.0.3
  synchronized: 3.3.1

  simple_barcode_scanner: 0.3.0
  freezed_annotation: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.15
  retrofit_generator: any
  json_serializable: any

  custom_lint: 0.7.5
  riverpod_lint: 2.6.5
  riverpod_generator: 2.6.5


flutter:
  uses-material-design: true

  assets:
    - res/drawables/
    - res/svg/

  fonts:
    - family: AppIcons
      fonts:
        - asset: res/fonts/app_icons.ttf
    - family: Avenir
      fonts:
        - asset: res/fonts/Avenir-Light.ttf
          weight: 300
        - asset: res/fonts/Avenir-Regular.ttf
          weight: 400
        - asset: res/fonts/Avenir-Medium.ttf
          weight: 500
        - asset: res/fonts/Avenir-Black.ttf
          weight: 900